CREATE DATABASE IF NOT EXISTS MDB_DB_NAME;

CREATE USER IF NOT EXISTS 'MDB_USER_NAME'@'%' IDENTIFIED BY 'MDB_USER_PASS';

GRANT ALL PRIVILEGES ON wordpress.* TO 'MDB_USER_NAME'@'%';

ALTER USER 'root'@'localhost' IDENTIFIED BY 'MDB_ROOT_PASS';

FLUSH PRIVILEGES;
